### ISSUE TITLE
Support for NativeScript 3.0 RC

### ISSUE THREAD

**Issue by Cae2** [Icenium/icenium-cli#1665]
Hello, just tried the version 3.7.1 (released today) and still cannot use in a NS 3.0 RC Project.

Do you have some ETA for that?

Thank you

**Comment by Mitko-Kerezov** [comment]
Hi @Cae2,

AppBuilder doesn't support release candidates for any NativeScript version.
The 3.0 RC is aimed primarily at plugin authors so that they may upgrade their plugins in order to conform with the breaking changes. That being said even if AppBuilder did support the release candidate one probably wouldn't be able to build and run an application due to the lack of plugins compatible with the new NativeScript version.

AppBuilder will however support the official 3.0 NativeScript version once that is released.

**Comment by Cae2** [comment]
thank you @Mitko-Kerezov 

I just downgraded to 2.5.4 to use appbuilder, gonna wait the stable version of NS. :)
